In [97]:
include("src\\ImportanceSampling.jl")
using ImportanceSampling
using Distributions

In [79]:
g!s = [((r, x) -> r .= 2*x, [1.0])
    ((r, x) -> begin
            y = first(x)
            r[1] = 5*y.^2
            r[2] = cos.(3*y)
            r[3] = sin.(3*y)
            r
        end, [2.0, 2, 1])]

2-element Array{Tuple{Function,Array{Float64,1}},1}:
 (#47, [1.0])          
 (#48, [2.0, 2.0, 1.0])

In [153]:
θs = last.(g!s)

2-element Array{Array{Float64,1},1}:
 [1.0]          
 [2.0, 2.0, 1.0]

In [156]:
cumsum(vcat(1, length.(θs)))

3-element Array{Int64,1}:
 1
 2
 5

In [114]:
t = zeros(2)
x = zeros(3)
gs[1](view(t, 1:1, 1), x)
gs[2](view(t, 2:2, 1), x)
t

2-element Array{Float64,1}:
 0.0079367
 0.0634936

In [119]:
pdf(MvNormal(eye(3)), zeros(3))

0.06349363593424096

In [117]:
qs[1]

ZeroMeanIsoNormal(
dim: 3
μ: [0.0, 0.0, 0.0]
Σ: [4.0 0.0 0.0; 0.0 4.0 0.0; 0.0 0.0 4.0]
)
