In [1]:
include("src\\ImportanceSampling.jl")
using Distributions
using ImportanceSampling
using Seaborn

In [2]:
p = Weibull(2, 4)
q = Exponential(2)
f!(r, x) = r[1:2] = Float64[x[1], x[1]^2]

is = ImportanceSampler(f!, 2, q, p=p)

N = 5000
X = rand(q, N)
;

In [4]:
t = zeros(2)
m = sum(f!(t, X[i]).*pdf(p, X[i])/pdf.(q, X[i]) for i in 1:N) ./ N
isapprox(mean(is), m)

false

In [5]:
mean(is) - [mean(p), var(p) + mean(p)^2]

2-element Array{Float64,1}:
 NaN
 NaN

# MV

In [ ]:
p = MvNormal(2.0*ones(2), eye(2))
q = MvTDist(1, zeros(2), eye(2)*5)
f!(r, x) = r[:] = vcat(x, x.^2)

is = ImportanceSampler(f!, 4, q, p=p)

N = 5000
X = rand(q, N)
;

In [48]:
update!(is, X=X)

ImportanceSampling.Diagnostic(5000, 5100.831515511719, 39068.02775873413, 405048.3541831882, 4.76868615717365e6)

In [58]:
t = zeros(4)
m = sum(f!(t, X[:, i]).*pdf(p, X[:, i])/pdf(q, X[:, i]) for i in 1:N) ./ N
isapprox(mean(is), m)

4-element Array{Float64,1}:
 2.07596
 2.03016
 5.25755
 5.05987

In [65]:
mean(is)

4-element Array{Float64,1}:
 2.07596
 2.03016
 5.25755
 5.05987

In [62]:
mean(is) - vcat(mean(p), var(p) + mean(p).^2)

4-element Array{Float64,1}:
 0.0759634
 0.0301567
 0.257546 
 0.0598705