In [1]:
include("..\\src\\ImportanceSampling.jl")
using ImportanceSampling
using Distributions
using Seaborn

In [2]:
p = MvNormal(2.0*ones(2), eye(2))
q = MvTDist(1, zeros(2), eye(2)*5)
f!(r, x) = r .= vcat(x, x.^2)

is = ImportanceSampler(f!, 4, q, p=p)
update!(is, batchsize=1000, nbatches=10)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] sqrt(::Array{Float64,2}) at .\deprecated.jl:57
 [3] _rand!(::Distributions.GenericMvTDist{Float64,PDMats.PDMat{Float64,Array{Float64,2}}}, ::Array{Float64,2}) at C:\Users\Hamza El-Saawy\.julia\v0.6\Distributions\src\multivariate\mvtdist.jl:176
 [4] rand!(::Distributions.GenericMvTDist{Float64,PDMats.PDMat{Float64,Array{Float64,2}}}, ::Array{Float64,2}) at C:\Users\Hamza El-Saawy\.julia\v0.6\Distributions\src\multivariates.jl:36
 [5] #_update!#31(::Bool, ::Array{Any,1}, ::Function, ::Val{true}, ::ImportanceSampling.ImportanceSampler, ::Void, ::Void, ::Void, ::Int64, ::Int64, ::Int64) at C:\Users\Hamza El-Saawy\Documents\school\stats362\project\src\importance_sampler.jl:211
 [6] #update!#13(::Void, ::Void, ::Void, ::Int64, ::Int64, ::Int64, ::Array{Any,1}, ::Function, ::ImportanceSampling.ImportanceSampler) at C:\Users\Hamza El-Saawy\Documents\school\stats362\project\src\importance_sampler.jl:63
 [7] (::ImportanceSam

ImportanceSampling.ImportanceSampler(Distributions.GenericMvTDist{Float64,PDMats.PDMat{Float64,Array{Float64,2}}}(
df: 1.0
dim: 2
zeromean: true
μ: [0.0, 0.0]
Σ: PDMats.PDMat{Float64,Array{Float64,2}}(2, [5.0 0.0; 0.0 5.0], Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
[2.23607 0.0; 0.0 2.23607])
)
, ImportanceSampling.MeanVariance{4}(10000, [19473.8, 19305.8, 49008.0, 48540.4], [5.83422e5 5.0781e5 1.56516e6 1.235e6; 5.0781e5 5.73519e5 1.24603e6 1.53381e6; 1.56516e6 1.24603e6 4.46438e6 3.00597e6; 1.235e6 1.53381e6 3.00597e6 4.38048e6]), ImportanceSampling.Diagnostic(10000, 9732.072656586979, 112737.19396266271, 1.8159411339600803e6, 3.346280169561414e7), ImportanceSampling.#22, f!)

In [3]:
m = mean(is)
m[1:2]

2-element Array{Float64,1}:
 1.94738
 1.93058

In [4]:
m[3:4] .- m[1:2].^2

2-element Array{Float64,1}:
 1.1085 
 1.12691

In [5]:
var(is)

4-element Array{Float64,1}:
 0.00583481
 0.00573577
 0.0446483 
 0.0438092 